SERVICE_NAME=${SERVICE_NAME}
ENVIRONMENT=${ENVIRONMENT}
LOGFIRE_TOKEN=${LOGFIRE_TOKEN}
LOGFIRE_TRACEPARENT=${LOGFIRE_TRACEPARENT}
LOG_LEVEL=${LOG_LEVEL}
CDP_HOST=localhost
CDP_PORT=9221
TIGRIS_BUCKET=${TIGRIS_BUCKET}
TIGRIS_ACCESS_KEY_ID=${TIGRIS_ACCESS_KEY_ID}
TIGRIS_SECRET_ACCESS_KEY=${TIGRIS_SECRET_ACCESS_KEY}
TIGRIS_ENDPOINT_URL=${TIGRIS_ENDPOINT_URL}
TIGRIS_REGION=${TIGRIS_REGION}
