OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
OTEL_EXPORTER_OTLP_HEADERS=${OTEL_EXPORTER_OTLP_HEADERS}
OTEL_SERVICE_NAME=${OTEL_SERVICE_NAME}
OTEL_LOG_LEVEL=${OTEL_LOG_LEVEL}
OTEL_TRACEPARENT=${OTEL_TRACEPARENT}
CDP_HOST=localhost
CDP_PORT=9221
