#!/command/with-contenv sh

# Substitute environment variables into config
sed -i \
  -e "s|\${SERVICE_NAME}|${SERVICE_NAME:-browser-trace}|g" \
  -e "s|\${ENVIRONMENT}|${ENVIRONMENT:-local}|g" \
  -e "s|\${LOGFIRE_TOKEN}|${LOGFIRE_TOKEN:-}|g" \
  -e "s|\${LOGFIRE_TRACEPARENT}|${LOGFIRE_TRACEPARENT:-}|g" \
  -e "s|\${LOG_LEVEL}|${LOG_LEVEL:-INFO}|g" \
  -e "s|\${TIGRIS_BUCKET}|${TIGRIS_BUCKET:-}|g" \
  -e "s|\${TIGRIS_ACCESS_KEY_ID}|${TIGRIS_ACCESS_KEY_ID:-}|g" \
  -e "s|\${TIGRIS_SECRET_ACCESS_KEY}|${TIGRIS_SECRET_ACCESS_KEY:-}|g" \
  -e "s|\${TIGRIS_ENDPOINT_URL}|${TIGRIS_ENDPOINT_URL:-}|g" \
  -e "s|\${TIGRIS_REGION}|${TIGRIS_REGION:-}|g" \
  /app/browser-trace.conf

# Wait for Chrome CDP
while ! socat -T1 -u OPEN:/dev/null TCP:127.0.0.1:9221 >/dev/null 2>&1; do
  sleep 1
done

export LOGFIRE_INSPECT_ARGUMENTS=false
exec /usr/local/bin/browser-trace /app/browser-trace.conf
