#!/command/with-contenv sh
export HOME=/home/user
export DISPLAY=${DISPLAY:-:99}
exec s6-setuidgid user cloak-browser --fingerprint-platform=windows --start-maximized --no-sandbox --no-first-run --disable-default-apps --no-default-browser-check --remote-debugging-port=9221 --disable-dev-shm-usage --use-gl=swiftshader --disable-features=OptimizationGuideModelDownloading,OptimizationHints,OptimizationTargetPrediction --disable-background-networking --disable-component-update --disable-domain-reliability --disable-sync --no-pings --user-data-dir=/home/user/chrome-profile --enable-logging=stderr --log-level=3 about:blank
